// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyfKbs1NSiZWnL9P-Slxg7jPQBwUKXPeQ',
    appId: '1:819855589515:web:acb4d8a5d427243ae0948e',
    messagingSenderId: '819855589515',
    projectId: 'fasum-j-8819b',
    authDomain: 'fasum-j-8819b.firebaseapp.com',
    storageBucket: 'fasum-j-8819b.firebasestorage.app',
    measurementId: 'G-EJKSD4XRLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpMh2F29EfpeMNJHl2AtF3wVZF9badjEI',
    appId: '1:819855589515:android:836542129be4c6f7e0948e',
    messagingSenderId: '819855589515',
    projectId: 'fasum-j-8819b',
    storageBucket: 'fasum-j-8819b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSONTxDOb85yFT69e5grryfbQjah9cNiM',
    appId: '1:669330915346:ios:1b08fc08d28b1c6726d8cb',
    messagingSenderId: '669330915346',
    projectId: 'fasum-apps-2418a',
    storageBucket: 'fasum-apps-2418a.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSONTxDOb85yFT69e5grryfbQjah9cNiM',
    appId: '1:669330915346:ios:1b08fc08d28b1c6726d8cb',
    messagingSenderId: '669330915346',
    projectId: 'fasum-apps-2418a',
    storageBucket: 'fasum-apps-2418a.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc4ckqUVa_5aKuXRXe47VTJguflpfoPj0',
    appId: '1:669330915346:web:2364717a5ed9344826d8cb',
    messagingSenderId: '669330915346',
    projectId: 'fasum-apps-2418a',
    authDomain: 'fasum-apps-2418a.firebaseapp.com',
    storageBucket: 'fasum-apps-2418a.firebasestorage.app',
    measurementId: 'G-QC9H85GBSZ',
  );

}