// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6rmfgqI6sHEjoY8Dnk7tjNyd9gUPetY',
    appId: '1:447177155709:web:2539d4c429492bf7abfd14',
    messagingSenderId: '447177155709',
    projectId: 'first-app-8e447',
    authDomain: 'first-app-8e447.firebaseapp.com',
    databaseURL: 'https://first-app-8e447-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-8e447.firebasestorage.app',
    measurementId: 'G-9SFW4NYZ5B',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1PTNMz6pDPi-i8u6sMFyxN8n_wJcIoeM',
    appId: '1:447177155709:ios:b6cc5daa70267e06abfd14',
    messagingSenderId: '447177155709',
    projectId: 'first-app-8e447',
    databaseURL: 'https://first-app-8e447-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-8e447.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1PTNMz6pDPi-i8u6sMFyxN8n_wJcIoeM',
    appId: '1:447177155709:ios:b6cc5daa70267e06abfd14',
    messagingSenderId: '447177155709',
    projectId: 'first-app-8e447',
    databaseURL: 'https://first-app-8e447-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-8e447.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu6rmfgqI6sHEjoY8Dnk7tjNyd9gUPetY',
    appId: '1:447177155709:web:5b73f0af043f8689abfd14',
    messagingSenderId: '447177155709',
    projectId: 'first-app-8e447',
    authDomain: 'first-app-8e447.firebaseapp.com',
    databaseURL: 'https://first-app-8e447-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-8e447.firebasestorage.app',
    measurementId: 'G-ZJNTV4C84D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRC2aMcqvLGvXk_DGZlGjBR3FosMLXREo',
    appId: '1:447177155709:android:2001479fc724e7deabfd14',
    messagingSenderId: '447177155709',
    projectId: 'first-app-8e447',
    databaseURL: 'https://first-app-8e447-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-8e447.firebasestorage.app',
  );

}